[workspace]
members = ["apps/ui/src-tauri"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
log = "0.4"
tauri = "2.0.0-alpha.8"
tauri-build = "2.0.0-alpha.4"
serde_json = "1"
thiserror = "1"

[workspace.package]
edition = "2021"
authors = [ "Tauri Programme within The Commons Conservancy" ]
license = "Apache-2.0 OR MIT"
rust-version = "1.72"

