/* tslint:disable */
/* eslint-disable */
/**
 * Fiber Example API
 * This is a sample swagger for Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: fiber@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "./configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "./common";
import type { RequestArgs } from "./base";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "./base";

/**
 *
 * @export
 * @interface FoodFood
 */
export interface FoodFood {
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  calcium?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  calories?: number;
  /**
   *
   * @type {string}
   * @memberof FoodFood
   */
  category?: string;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  cholesterol?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  concentrated?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  fiber?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  fnvl?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  id?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  iron?: number;
  /**
   *
   * @type {string}
   * @memberof FoodFood
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  potassium?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  protein?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  rate?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  saturated?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  sodium?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  sugar?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  totalFat?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  total_carbohydrate?: number;
  /**
   *
   * @type {number}
   * @memberof FoodFood
   */
  vitamin_d?: number;
}
/**
 *
 * @export
 * @interface FoodWriteFood
 */
export interface FoodWriteFood {
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  calcium?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  calories?: number;
  /**
   *
   * @type {string}
   * @memberof FoodWriteFood
   */
  category?: string;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  cholesterol?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  concentrated?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  fiber?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  fnvl?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  iron?: number;
  /**
   *
   * @type {string}
   * @memberof FoodWriteFood
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  potassium?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  protein?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  rate?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  saturated?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  sodium?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  sugar?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  totalFat?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  total_carbohydrate?: number;
  /**
   *
   * @type {number}
   * @memberof FoodWriteFood
   */
  vitamin_d?: number;
}

/**
 * FoodApi - axios parameter creator
 * @export
 */
export const FoodApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     * Get list food nutrients and rate
     * @summary Get list food details api
     * @param {number} [page] Page
     * @param {number} [pageSize] Page Size
     * @param {FoodsGetSortEnum} [sort] Sort direction
     * @param {string} [search] Search term
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsGet: async (
      page?: number,
      pageSize?: number,
      sort?: FoodsGetSortEnum,
      search?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/foods`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (page !== undefined) {
        localVarQueryParameter["page"] = page;
      }

      if (pageSize !== undefined) {
        localVarQueryParameter["pageSize"] = pageSize;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (search !== undefined) {
        localVarQueryParameter["search"] = search;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Delete food nutrients and rate for custom HSR
     * @summary Delete food api
     * @param {number} id Food ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsIdDelete: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("foodsIdDelete", "id", id);
      const localVarPath = `/foods/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get food nutrients and rate
     * @summary Get food details api
     * @param {number} id Food ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsIdGet: async (
      id: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("foodsIdGet", "id", id);
      const localVarPath = `/foods/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Update food nutrients and rate for custom HSR
     * @summary Update food api
     * @param {number} id Food ID
     * @param {FoodWriteFood} post Update food body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsIdPut: async (
      id: number,
      post: FoodWriteFood,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("foodsIdPut", "id", id);
      // verify required parameter 'post' is not null or undefined
      assertParamExists("foodsIdPut", "post", post);
      const localVarPath = `/foods/{id}`.replace(
        `{${"id"}}`,
        encodeURIComponent(String(id)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        post,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Insert food nutrients and rate for custom HSR
     * @summary Create food api
     * @param {FoodWriteFood} post Create food body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsPost: async (
      post: FoodWriteFood,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'post' is not null or undefined
      assertParamExists("foodsPost", "post", post);
      const localVarPath = `/foods`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        post,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * FoodApi - functional programming interface
 * @export
 */
export const FoodApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = FoodApiAxiosParamCreator(configuration);
  return {
    /**
     * Get list food nutrients and rate
     * @summary Get list food details api
     * @param {number} [page] Page
     * @param {number} [pageSize] Page Size
     * @param {FoodsGetSortEnum} [sort] Sort direction
     * @param {string} [search] Search term
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async foodsGet(
      page?: number,
      pageSize?: number,
      sort?: FoodsGetSortEnum,
      search?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FoodFood>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.foodsGet(
        page,
        pageSize,
        sort,
        search,
        options,
      );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["FoodApi.foodsGet"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     * Delete food nutrients and rate for custom HSR
     * @summary Delete food api
     * @param {number} id Food ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async foodsIdDelete(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FoodFood>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.foodsIdDelete(
        id,
        options,
      );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["FoodApi.foodsIdDelete"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     * Get food nutrients and rate
     * @summary Get food details api
     * @param {number} id Food ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async foodsIdGet(
      id: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FoodFood>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.foodsIdGet(
        id,
        options,
      );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["FoodApi.foodsIdGet"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     * Update food nutrients and rate for custom HSR
     * @summary Update food api
     * @param {number} id Food ID
     * @param {FoodWriteFood} post Update food body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async foodsIdPut(
      id: number,
      post: FoodWriteFood,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FoodFood>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.foodsIdPut(
        id,
        post,
        options,
      );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["FoodApi.foodsIdPut"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
    /**
     * Insert food nutrients and rate for custom HSR
     * @summary Create food api
     * @param {FoodWriteFood} post Create food body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async foodsPost(
      post: FoodWriteFood,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<FoodFood>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.foodsPost(
        post,
        options,
      );
      const index = configuration?.serverIndex ?? 0;
      const operationBasePath =
        operationServerMap["FoodApi.foodsPost"]?.[index]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, operationBasePath || basePath);
    },
  };
};

/**
 * FoodApi - factory interface
 * @export
 */
export const FoodApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = FoodApiFp(configuration);
  return {
    /**
     * Get list food nutrients and rate
     * @summary Get list food details api
     * @param {number} [page] Page
     * @param {number} [pageSize] Page Size
     * @param {FoodsGetSortEnum} [sort] Sort direction
     * @param {string} [search] Search term
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsGet(
      page?: number,
      pageSize?: number,
      sort?: FoodsGetSortEnum,
      search?: string,
      options?: any,
    ): AxiosPromise<FoodFood> {
      return localVarFp
        .foodsGet(page, pageSize, sort, search, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Delete food nutrients and rate for custom HSR
     * @summary Delete food api
     * @param {number} id Food ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsIdDelete(id: number, options?: any): AxiosPromise<FoodFood> {
      return localVarFp
        .foodsIdDelete(id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Get food nutrients and rate
     * @summary Get food details api
     * @param {number} id Food ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsIdGet(id: number, options?: any): AxiosPromise<FoodFood> {
      return localVarFp
        .foodsIdGet(id, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Update food nutrients and rate for custom HSR
     * @summary Update food api
     * @param {number} id Food ID
     * @param {FoodWriteFood} post Update food body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsIdPut(
      id: number,
      post: FoodWriteFood,
      options?: any,
    ): AxiosPromise<FoodFood> {
      return localVarFp
        .foodsIdPut(id, post, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Insert food nutrients and rate for custom HSR
     * @summary Create food api
     * @param {FoodWriteFood} post Create food body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    foodsPost(post: FoodWriteFood, options?: any): AxiosPromise<FoodFood> {
      return localVarFp
        .foodsPost(post, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * FoodApi - object-oriented interface
 * @export
 * @class FoodApi
 * @extends {BaseAPI}
 */
export class FoodApi extends BaseAPI {
  /**
   * Get list food nutrients and rate
   * @summary Get list food details api
   * @param {number} [page] Page
   * @param {number} [pageSize] Page Size
   * @param {FoodsGetSortEnum} [sort] Sort direction
   * @param {string} [search] Search term
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FoodApi
   */
  public foodsGet(
    page?: number,
    pageSize?: number,
    sort?: FoodsGetSortEnum,
    search?: string,
    options?: RawAxiosRequestConfig,
  ) {
    return FoodApiFp(this.configuration)
      .foodsGet(page, pageSize, sort, search, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Delete food nutrients and rate for custom HSR
   * @summary Delete food api
   * @param {number} id Food ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FoodApi
   */
  public foodsIdDelete(id: number, options?: RawAxiosRequestConfig) {
    return FoodApiFp(this.configuration)
      .foodsIdDelete(id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get food nutrients and rate
   * @summary Get food details api
   * @param {number} id Food ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FoodApi
   */
  public foodsIdGet(id: number, options?: RawAxiosRequestConfig) {
    return FoodApiFp(this.configuration)
      .foodsIdGet(id, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Update food nutrients and rate for custom HSR
   * @summary Update food api
   * @param {number} id Food ID
   * @param {FoodWriteFood} post Update food body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FoodApi
   */
  public foodsIdPut(
    id: number,
    post: FoodWriteFood,
    options?: RawAxiosRequestConfig,
  ) {
    return FoodApiFp(this.configuration)
      .foodsIdPut(id, post, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Insert food nutrients and rate for custom HSR
   * @summary Create food api
   * @param {FoodWriteFood} post Create food body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof FoodApi
   */
  public foodsPost(post: FoodWriteFood, options?: RawAxiosRequestConfig) {
    return FoodApiFp(this.configuration)
      .foodsPost(post, options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * @export
 */
export const FoodsGetSortEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type FoodsGetSortEnum =
  (typeof FoodsGetSortEnum)[keyof typeof FoodsGetSortEnum];
